
GET http://localhost:8881/doc/list?page=1&size=10
###

GET http://localhost:8881/doc/all/1
###

GET http://localhost:8881/doc/find-content/1
token: 562927127100526592

###

GET http://localhost:8881/doc/vote/1
token: 562927127100526592

###

POST http://localhost:8881/doc/save
Content-Type: application/json

{
  "parent": 0,
  "ebookId": 1,
  "name": "222",
  "content": "123",
  "sort": 209
}

###

POST http://localhost:8881/doc/save
Content-Type: application/json

{
  "id": 999,
  "parent": 0,
  "ebookId": 1,
  "name": "aaaa",
  "content": "jsdljklds",
  "sort": 209
}

###

DELETE http://localhost:8881/doc/delete/562181389617860608

###


GET http://localhost:8881/doc/find-content/999
###